# Generated by Django 5.2.7 on 2025-10-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invioce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invioce_no', models.CharField(max_length=50, unique=True)),
                ('invioce_date', models.DateField(auto_now_add=True)),
                ('vat_date', models.DateField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=225)),
                ('customer_address', models.TextField()),
                ('customer_contract_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
