# Generated by Django 5.2.7 on 2025-10-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invioce',
            new_name='Invoice',
        ),
    ]
