# Generated by Django 5.2.7 on 2025-10-24 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_rename_invioce_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_contract_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_po_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invioce_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invioce_no',
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default='INV-0001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
