# Generated by Django 5.2.7 on 2025-10-24 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_customer_contract_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract_no',
            field=models.CharField(blank=True, default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='po_no',
            field=models.CharField(blank=True, default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('unit_rate', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
        ),
    ]
