# Generated by Django 5.2.7 on 2025-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_created_at_alter_invoice_contract_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='template_image',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_templates/'),
        ),
    ]
